README changes
appwrite/sdk-for-node pull request #43
Opened 2022-10-03 15:31 UTC by keul

## What does this PR do?

Fix some readme instruction that didn't worked for me on appwrite 1.1

- `ID.xxx` is undefined
- `phone` parameter is before password. By not providing it I get an HTTP 400 ("Invalid phone: Phone number must start with a '+' can have a maximum of fifteen digits")

2022-10-06 23:18 UTC, stnguyen90 commented
@keul Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-10-06 23:18 UTC, stnguyen90 approved these changes

2022-10-14 08:29 UTC, christyjacob4 commented
@stnguyen90 @keul These changes should be made in the appwrite repo here
https://github.com/appwrite/appwrite/blob/master/docs/sdks/nodejs/GETTING_STARTED.md

2022-10-14 08:30 UTC, christyjacob4 requested changes
@stnguyen90 @keul These changes should be made in the appwrite repo here
https://github.com/appwrite/appwrite/blob/master/docs/sdks/nodejs/GETTING_STARTED.md

2022-10-14 09:59 UTC, keul commented
@christyjacob4 sorry I don't fully understand. This repo will remain with a wrong README? Or it is someway automatically synced with the README you are referring to?

2022-10-18 07:49 UTC, christyjacob4 commented
@keul This repository is read only. 

![Screenshot 2022-10-18 at 11 48 36 AM](https://user-images.githubusercontent.com/20852629/196369015-47e5e275-e9fb-412f-b12e-13e7b323e4b8.png)

We generate all the code and text content in this repository using the [sdk-generator](https://github.com/appwrite/sdk-generator)

**Your change is completely valid.** You just need to make it in the sdk-generator repo in this file
https://github.com/appwrite/appwrite/blob/master/docs/sdks/nodejs/GETTING_STARTED.md

Let me know if you have any questions

2022-10-18 10:18 UTC, keul commented
Thanks for clarification!

2022-10-19 07:33 UTC, christyjacob4 commented
@keul Happy to help. Looking forward to your contribution :)

2022-10-20 18:32 UTC, closed without merging